server:
  port: 8081
  
# Links
link:
  twseopenapi:
    listedcompanyinfo: https://openapi.twse.com.tw/v1/opendata/t187ap03_L
  twse:
    stockhistoryinfo: https://www.twse.com.tw/exchangeReport/STOCK_DAY